# Generated by Django 5.1 on 2024-09-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240902_0649'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE INDEX IF NOT EXISTS universalcontent_title_trigram_idx ON api_universalcontent USING gin (title gin_trgm_ops);
            CREATE INDEX IF NOT EXISTS universalcontent_content_trigram_idx ON api_universalcontent USING gin (content gin_trgm_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS universalcontent_title_trigram_idx;
            DROP INDEX IF EXISTS universalcontent_content_trigram_idx;
            """
        ),
    ]
