# Generated by Django 5.1.1 on 2024-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240902_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=255)),
                ('career_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/careers/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/services/')),
            ],
        ),
    ]
