# Generated by Django 5.1.1 on 2024-09-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_careercontact_servicecontact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='careercontact',
            table='careers_contact',
        ),
        migrations.AlterModelTable(
            name='servicecontact',
            table='service_contact',
        ),
    ]
