# Generated by Django 5.1 on 2024-09-10 19:48

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_websitesection'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
    ]
